; PhoneContacts indexes (see data/phone/phone_contacts.asm)
	const_def
	const PHONE_00
	const PHONE_MOM
	const PHONE_OAK
	const PHONE_BILL
	const PHONE_ELM
	const PHONE_LYRA
	const PHONE_SCHOOLBOY_JACK
	const PHONE_POKEFAN_BEVERLY
	const PHONE_SAILOR_HUEY
	const PHONE_POKEFANM_BRANDON
	const PHONE_FIREBREATHER_WALT
	const PHONE_COOLTRAINERM_GAVEN
	const PHONE_COOLTRAINERF_BETH
	const PHONE_BIRDKEEPER_JOSE
	const PHONE_COOLTRAINERF_REENA
	const PHONE_YOUNGSTER_JOEY
	const PHONE_BUG_CATCHER_WADE
	const PHONE_FISHER_RALPH
	const PHONE_PICNICKER_LIZ
	const PHONE_HIKER_ANTHONY
	const PHONE_CAMPER_TODD
	const PHONE_PICNICKER_GINA
	const PHONE_JUGGLER_IRWIN
	const PHONE_BUG_CATCHER_ARNIE
	const PHONE_SCHOOLBOY_ALAN
	const PHONE_LASS_KRISE
	const PHONE_LASS_DANA
	const PHONE_SCHOOLBOY_CHAD
	const PHONE_POKEFANM_DEREK
	const PHONE_FISHER_TULLY
	const PHONE_POKEMANIAC_BRENT
	const PHONE_PICNICKER_TIFFANY
	const PHONE_BIRDKEEPER_VANCE
	const PHONE_FISHER_WILTON
	const PHONE_BLACKBELT_KENJI
	const PHONE_HIKER_PARRY
	const PHONE_PICNICKER_ERIN
	const PHONE_GENTLEMAN_ALFRED
	const PHONE_BUG_MANIAC_DOUG
	const PHONE_BUG_MANIAC_ROB
	const PHONE_FISHER_KYLE
	const PHONE_CAMPER_TANNER
	const PHONE_HIKER_KENNY
	const PHONE_COUPLE_TIM_AND_SUE
	const PHONE_FISHER_KYLER
	const PHONE_SCHOOLBOY_TORIN
	const PHONE_SCHOOLBOY_BILLY
	const PHONE_TEACHER_HILLARY
	const PHONE_TWINS_KAY_AND_TIA
	const PHONE_OFFICERF_JAMIE
	const PHONE_BIKER_AIDEN
	const PHONE_BIKER_DALE
	const PHONE_BIKER_REILLY
	const PHONE_BUENA
DEF NUM_PHONE_CONTACTS EQU const_value - 1

; wDailyRematchFlags indexes
	const_def
	const REMATCH_CONTACT_JACK
	const REMATCH_CONTACT_HUEY
	const REMATCH_CONTACT_GAVEN
	const REMATCH_CONTACT_BETH
	const REMATCH_CONTACT_JOSE
	const REMATCH_CONTACT_REENA
	const REMATCH_CONTACT_JOEY
	const REMATCH_CONTACT_WADE
	const REMATCH_CONTACT_RALPH
	const REMATCH_CONTACT_LIZ
	const REMATCH_CONTACT_ANTHONY
	const REMATCH_CONTACT_TODD
	const REMATCH_CONTACT_GINA
	const REMATCH_CONTACT_ARNIE
	const REMATCH_CONTACT_ALAN
	const REMATCH_CONTACT_DANA
	const REMATCH_CONTACT_CHAD
	const REMATCH_CONTACT_TULLY
	const REMATCH_CONTACT_BRENT
	const REMATCH_CONTACT_TIFFANY
	const REMATCH_CONTACT_VANCE
	const REMATCH_CONTACT_WILTON
	const REMATCH_CONTACT_PARRY
	const REMATCH_CONTACT_ERIN
	const REMATCH_CONTACT_BRANDON
	const REMATCH_CONTACT_WALT
	const REMATCH_CONTACT_KRISE
	const REMATCH_CONTACT_ALFRED
	const REMATCH_CONTACT_DOUG
	const REMATCH_CONTACT_ROB
	const REMATCH_CONTACT_KYLE
	const REMATCH_CONTACT_TANNER
	const REMATCH_CONTACT_KENNY
	const REMATCH_CONTACT_TIM_AND_SUE
	const REMATCH_CONTACT_JAMIE
	const REMATCH_CONTACT_TORIN
	const REMATCH_CONTACT_BILLY
	const REMATCH_CONTACT_HILLARY
	const REMATCH_CONTACT_KAY_AND_TIA
	const REMATCH_CONTACT_AIDEN
	const REMATCH_CONTACT_DALE
	const REMATCH_CONTACT_REILLY
	const REMATCH_CONTACT_KYLER
DEF NUM_REMATCH_CONTACTS EQU const_value

; Keep the historical four-byte save allocation in place. Extension bytes
; live in reserved saved padding so later fields do not shift.
DEF REMATCH_FLAG_BASE_BYTES EQU 4
DEF REMATCH_FLAG_EXTENSION_BYTES EQU 2
DEF REMATCH_FLAG_BYTES EQU REMATCH_FLAG_BASE_BYTES + REMATCH_FLAG_EXTENSION_BYTES
DEF REMATCH_FLAG_CAPACITY EQU REMATCH_FLAG_BYTES * 8

	assert NUM_REMATCH_CONTACTS == 43
	assert NUM_REMATCH_CONTACTS <= REMATCH_FLAG_CAPACITY

; wDailyPhoneTimeOfDayFlags indexes.
; These deliberately match REMATCH_CONTACT_* so a contact ID can address both
; the pending-rematch bitset and its once-per-day schedule-window bitset.
DEF REMATCH_SCHEDULE_JACK    EQU REMATCH_CONTACT_JACK
DEF REMATCH_SCHEDULE_HUEY    EQU REMATCH_CONTACT_HUEY
DEF REMATCH_SCHEDULE_GAVEN   EQU REMATCH_CONTACT_GAVEN
DEF REMATCH_SCHEDULE_BETH    EQU REMATCH_CONTACT_BETH
DEF REMATCH_SCHEDULE_JOSE    EQU REMATCH_CONTACT_JOSE
DEF REMATCH_SCHEDULE_REENA   EQU REMATCH_CONTACT_REENA
DEF REMATCH_SCHEDULE_JOEY    EQU REMATCH_CONTACT_JOEY
DEF REMATCH_SCHEDULE_WADE    EQU REMATCH_CONTACT_WADE
DEF REMATCH_SCHEDULE_RALPH   EQU REMATCH_CONTACT_RALPH
DEF REMATCH_SCHEDULE_LIZ     EQU REMATCH_CONTACT_LIZ
DEF REMATCH_SCHEDULE_ANTHONY EQU REMATCH_CONTACT_ANTHONY
DEF REMATCH_SCHEDULE_TODD    EQU REMATCH_CONTACT_TODD
DEF REMATCH_SCHEDULE_GINA    EQU REMATCH_CONTACT_GINA
DEF REMATCH_SCHEDULE_ARNIE   EQU REMATCH_CONTACT_ARNIE
DEF REMATCH_SCHEDULE_ALAN    EQU REMATCH_CONTACT_ALAN
DEF REMATCH_SCHEDULE_DANA    EQU REMATCH_CONTACT_DANA
DEF REMATCH_SCHEDULE_CHAD    EQU REMATCH_CONTACT_CHAD
DEF REMATCH_SCHEDULE_TULLY   EQU REMATCH_CONTACT_TULLY
DEF REMATCH_SCHEDULE_BRENT   EQU REMATCH_CONTACT_BRENT
DEF REMATCH_SCHEDULE_TIFFANY EQU REMATCH_CONTACT_TIFFANY
DEF REMATCH_SCHEDULE_VANCE   EQU REMATCH_CONTACT_VANCE
DEF REMATCH_SCHEDULE_WILTON  EQU REMATCH_CONTACT_WILTON
DEF REMATCH_SCHEDULE_PARRY   EQU REMATCH_CONTACT_PARRY
DEF REMATCH_SCHEDULE_ERIN    EQU REMATCH_CONTACT_ERIN
DEF REMATCH_SCHEDULE_BRANDON EQU REMATCH_CONTACT_BRANDON
DEF REMATCH_SCHEDULE_WALT    EQU REMATCH_CONTACT_WALT
DEF REMATCH_SCHEDULE_KRISE   EQU REMATCH_CONTACT_KRISE
DEF REMATCH_SCHEDULE_ALFRED  EQU REMATCH_CONTACT_ALFRED
DEF REMATCH_SCHEDULE_DOUG    EQU REMATCH_CONTACT_DOUG
DEF REMATCH_SCHEDULE_ROB     EQU REMATCH_CONTACT_ROB
DEF REMATCH_SCHEDULE_KYLE    EQU REMATCH_CONTACT_KYLE
DEF REMATCH_SCHEDULE_TANNER  EQU REMATCH_CONTACT_TANNER
DEF REMATCH_SCHEDULE_KENNY   EQU REMATCH_CONTACT_KENNY
DEF REMATCH_SCHEDULE_TIM_AND_SUE EQU REMATCH_CONTACT_TIM_AND_SUE
DEF REMATCH_SCHEDULE_JAMIE   EQU REMATCH_CONTACT_JAMIE
DEF REMATCH_SCHEDULE_TORIN   EQU REMATCH_CONTACT_TORIN
DEF REMATCH_SCHEDULE_BILLY   EQU REMATCH_CONTACT_BILLY
DEF REMATCH_SCHEDULE_HILLARY EQU REMATCH_CONTACT_HILLARY
DEF REMATCH_SCHEDULE_KAY_AND_TIA EQU REMATCH_CONTACT_KAY_AND_TIA
DEF REMATCH_SCHEDULE_AIDEN   EQU REMATCH_CONTACT_AIDEN
DEF REMATCH_SCHEDULE_DALE    EQU REMATCH_CONTACT_DALE
DEF REMATCH_SCHEDULE_REILLY  EQU REMATCH_CONTACT_REILLY
DEF REMATCH_SCHEDULE_KYLER   EQU REMATCH_CONTACT_KYLER
DEF NUM_REMATCH_SCHEDULES EQU NUM_REMATCH_CONTACTS

; The schedule bitset uses the same six-byte capacity as pending rematches.
DEF REMATCH_SCHEDULE_FLAG_BASE_BYTES EQU 4
DEF REMATCH_SCHEDULE_FLAG_EXTENSION_BYTES EQU 2
DEF REMATCH_SCHEDULE_FLAG_BYTES EQU REMATCH_SCHEDULE_FLAG_BASE_BYTES + REMATCH_SCHEDULE_FLAG_EXTENSION_BYTES
DEF REMATCH_SCHEDULE_FLAG_CAPACITY EQU REMATCH_SCHEDULE_FLAG_BYTES * 8

DEF REMATCH_SCHEDULE_MORNING   EQU 1 << MORN
DEF REMATCH_SCHEDULE_AFTERNOON EQU 1 << DAY
DEF REMATCH_SCHEDULE_DAY_EVE   EQU (1 << DAY) | (1 << EVE)
DEF REMATCH_SCHEDULE_NITE      EQU 1 << NITE
DEF REMATCH_SCHEDULE_NIGHT     EQU (1 << EVE) | (1 << NITE)

	assert REMATCH_SCHEDULE_JACK == 0
	assert REMATCH_SCHEDULE_KYLER == NUM_REMATCH_SCHEDULES - 1
	assert NUM_REMATCH_SCHEDULES == 43
	assert NUM_REMATCH_SCHEDULES <= REMATCH_SCHEDULE_FLAG_CAPACITY
	assert NUM_REMATCH_SCHEDULES == NUM_ENGINE_REMATCH_SCHEDULES
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_JACK == ENGINE_REMATCH_SCHEDULE_JACK
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_HUEY == ENGINE_REMATCH_SCHEDULE_HUEY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_GAVEN == ENGINE_REMATCH_SCHEDULE_GAVEN
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_BETH == ENGINE_REMATCH_SCHEDULE_BETH
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_JOSE == ENGINE_REMATCH_SCHEDULE_JOSE
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_REENA == ENGINE_REMATCH_SCHEDULE_REENA
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_JOEY == ENGINE_REMATCH_SCHEDULE_JOEY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_WADE == ENGINE_REMATCH_SCHEDULE_WADE
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_RALPH == ENGINE_REMATCH_SCHEDULE_RALPH
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_LIZ == ENGINE_REMATCH_SCHEDULE_LIZ
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_ANTHONY == ENGINE_REMATCH_SCHEDULE_ANTHONY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_TODD == ENGINE_REMATCH_SCHEDULE_TODD
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_GINA == ENGINE_REMATCH_SCHEDULE_GINA
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_ARNIE == ENGINE_REMATCH_SCHEDULE_ARNIE
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_ALAN == ENGINE_REMATCH_SCHEDULE_ALAN
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_DANA == ENGINE_REMATCH_SCHEDULE_DANA
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_CHAD == ENGINE_REMATCH_SCHEDULE_CHAD
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_TULLY == ENGINE_REMATCH_SCHEDULE_TULLY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_BRENT == ENGINE_REMATCH_SCHEDULE_BRENT
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_TIFFANY == ENGINE_REMATCH_SCHEDULE_TIFFANY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_VANCE == ENGINE_REMATCH_SCHEDULE_VANCE
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_WILTON == ENGINE_REMATCH_SCHEDULE_WILTON
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_PARRY == ENGINE_REMATCH_SCHEDULE_PARRY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_ERIN == ENGINE_REMATCH_SCHEDULE_ERIN
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_BRANDON == ENGINE_REMATCH_SCHEDULE_BRANDON
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_WALT == ENGINE_REMATCH_SCHEDULE_WALT
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_KRISE == ENGINE_REMATCH_SCHEDULE_KRISE
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_ALFRED == ENGINE_REMATCH_SCHEDULE_ALFRED
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_DOUG == ENGINE_REMATCH_SCHEDULE_DOUG
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_ROB == ENGINE_REMATCH_SCHEDULE_ROB
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_KYLE == ENGINE_REMATCH_SCHEDULE_KYLE
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_TANNER == ENGINE_REMATCH_SCHEDULE_TANNER
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_KENNY == ENGINE_REMATCH_SCHEDULE_KENNY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_TIM_AND_SUE == ENGINE_REMATCH_SCHEDULE_TIM_AND_SUE
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_JAMIE == ENGINE_REMATCH_SCHEDULE_JAMIE
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_TORIN == ENGINE_REMATCH_SCHEDULE_TORIN
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_BILLY == ENGINE_REMATCH_SCHEDULE_BILLY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_HILLARY == ENGINE_REMATCH_SCHEDULE_HILLARY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_KAY_AND_TIA == ENGINE_REMATCH_SCHEDULE_KAY_AND_TIA
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_AIDEN == ENGINE_REMATCH_SCHEDULE_AIDEN
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_DALE == ENGINE_REMATCH_SCHEDULE_DALE
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_REILLY == ENGINE_REMATCH_SCHEDULE_REILLY
	assert ENGINE_REMATCH_SCHEDULE_JACK + REMATCH_SCHEDULE_KYLER == ENGINE_REMATCH_SCHEDULE_KYLER

; Canonical outcomes for rematch-contact phone event arbitration.
; PHONE_EVENT_NONE is reserved for "no selectable event"; the remaining values
; are stable selector results. Persistent outcomes create or announce state
; the player can act on (rematch, swarm, gift). Rare reports and specials are
; informational/world-event outcomes, while flavor is the generic fallback.
	const_def
	const PHONE_EVENT_NONE
	const PHONE_EVENT_REMATCH
	const PHONE_EVENT_SWARM
	const PHONE_EVENT_GIFT
	const PHONE_EVENT_RARE_REPORT
	const PHONE_EVENT_SPECIAL
	const PHONE_EVENT_FLAVOR
DEF NUM_PHONE_EVENTS EQU const_value

; Selector results are separate from the broad capabilities used to gate
; entries. The original category results deliberately retain their numeric
; PHONE_EVENT_* values.
DEF PHONE_EVENT_RESULT_NONE        EQU PHONE_EVENT_NONE
DEF PHONE_EVENT_RESULT_REMATCH     EQU PHONE_EVENT_REMATCH
DEF PHONE_EVENT_RESULT_SWARM       EQU PHONE_EVENT_SWARM
DEF PHONE_EVENT_RESULT_GIFT        EQU PHONE_EVENT_GIFT
DEF PHONE_EVENT_RESULT_RARE_REPORT EQU PHONE_EVENT_RARE_REPORT
DEF PHONE_EVENT_RESULT_SPECIAL     EQU PHONE_EVENT_SPECIAL
DEF PHONE_EVENT_RESULT_FLAVOR      EQU PHONE_EVENT_FLAVOR
	const_def NUM_PHONE_EVENTS
	const PHONE_EVENT_RESULT_TRIVIA
	const PHONE_EVENT_RESULT_WRONG_NUMBER
	const PHONE_EVENT_RESULT_GOSSIP
	const PHONE_EVENT_RESULT_FAMILY
DEF NUM_PHONE_EVENT_RESULTS EQU const_value

; Capabilities describe reachable outcomes only. They do not encode selection
; order, odds, or priority.
DEF PHONE_EVENT_CAP_REMATCH     EQU 1 << (PHONE_EVENT_REMATCH - 1)
DEF PHONE_EVENT_CAP_SWARM       EQU 1 << (PHONE_EVENT_SWARM - 1)
DEF PHONE_EVENT_CAP_GIFT        EQU 1 << (PHONE_EVENT_GIFT - 1)
DEF PHONE_EVENT_CAP_RARE_REPORT EQU 1 << (PHONE_EVENT_RARE_REPORT - 1)
DEF PHONE_EVENT_CAP_SPECIAL     EQU 1 << (PHONE_EVENT_SPECIAL - 1)
DEF PHONE_EVENT_CAP_FLAVOR      EQU 1 << (PHONE_EVENT_FLAVOR - 1)
DEF NUM_PHONE_EVENT_CAPABILITIES EQU NUM_PHONE_EVENTS - 1
; Entry-local policy flag stored in the capability byte. A disabled nonterminal
; entry with this flag still consumes and discards its configured random roll.
DEF PHONE_EVENT_ROLL_WHEN_DISABLED EQU 1 << 7
DEF PHONE_EVENT_CAPABILITY_FLAG_MASK EQU PHONE_EVENT_ROLL_WHEN_DISABLED
; Transient selector input flag. This shares the staged candidate byte but is
; stripped before capability gating; it is never stored in SRAM.
DEF PHONE_EVENT_USE_REPEAT_POLICY EQU 1 << 7
DEF PHONE_EVENT_CAP_MASK EQU (1 << NUM_PHONE_EVENT_CAPABILITIES) - 1
DEF PHONE_EVENT_SELECTION_ENTRY_SIZE EQU 4
DEF MAX_PHONE_EVENT_SELECTION_ENTRIES EQU NUM_PHONE_EVENT_CAPABILITIES

	assert PHONE_EVENT_REMATCH == 1
	assert PHONE_EVENT_FLAVOR == NUM_PHONE_EVENTS - 1
	assert PHONE_EVENT_FLAVOR == 6
	assert NUM_PHONE_EVENT_CAPABILITIES <= 7
	assert PHONE_EVENT_RESULT_NONE == 0
	assert PHONE_EVENT_RESULT_REMATCH == 1
	assert PHONE_EVENT_RESULT_FLAVOR == PHONE_EVENT_FLAVOR
	assert PHONE_EVENT_RESULT_TRIVIA == NUM_PHONE_EVENTS
	assert PHONE_EVENT_RESULT_FAMILY == 10
	assert NUM_PHONE_EVENT_RESULTS <= $100
	assert PHONE_EVENT_ROLL_WHEN_DISABLED == $80
	assert PHONE_EVENT_CAPABILITY_FLAG_MASK == PHONE_EVENT_ROLL_WHEN_DISABLED
	assert PHONE_EVENT_ROLL_WHEN_DISABLED >= NUM_PHONE_EVENTS
	assert PHONE_EVENT_FLAVOR & PHONE_EVENT_CAPABILITY_FLAG_MASK == 0
	assert (NUM_PHONE_EVENTS - 1) & PHONE_EVENT_CAPABILITY_FLAG_MASK == 0
	assert PHONE_EVENT_USE_REPEAT_POLICY == $80
	assert PHONE_EVENT_CAP_FLAVOR < PHONE_EVENT_USE_REPEAT_POLICY
	assert PHONE_EVENT_CAP_MASK & PHONE_EVENT_USE_REPEAT_POLICY == 0
	assert (PHONE_EVENT_CAP_REMATCH | PHONE_EVENT_CAP_SWARM | PHONE_EVENT_CAP_GIFT | PHONE_EVENT_CAP_RARE_REPORT | PHONE_EVENT_CAP_SPECIAL | PHONE_EVENT_CAP_FLAVOR) & ~PHONE_EVENT_CAP_MASK == 0
	assert PHONE_EVENT_SELECTION_ENTRY_SIZE == 4
	assert MAX_PHONE_EVENT_SELECTION_ENTRIES <= 8

; SpecialPhoneCallList indexes (see data/phone/special_calls.asm)
	const_def
	const SPECIALCALL_NONE
	const SPECIALCALL_POKERUS
	const SPECIALCALL_ROBBED
	const SPECIALCALL_ASSISTANT
	const SPECIALCALL_WEIRDBROADCAST
	const SPECIALCALL_SSTICKET
	const SPECIALCALL_BIKESHOP
	const SPECIALCALL_WORRIED
	const SPECIALCALL_MASTERBALL
	const SPECIALCALL_YELLOWFOREST
	const SPECIALCALL_FIRSTBADGE
	const SPECIALCALL_SECONDBADGE
	const SPECIALCALL_LYRASEGG
DEF NUM_SPECIALCALLS EQU const_value - 1
DEF SPECIALCALL_SIZE EQU 6

; phone struct members
rsreset
DEF PHONE_CONTACT_TRAINER_CLASS  rb
DEF PHONE_CONTACT_TRAINER_NUMBER rb
DEF PHONE_CONTACT_MAP_GROUP      rb
DEF PHONE_CONTACT_MAP_NUMBER     rb
DEF PHONE_CONTACT_SCRIPT1_TIME   rb
DEF PHONE_CONTACT_SCRIPT1_BANK   rb
DEF PHONE_CONTACT_SCRIPT1_ADDR   rw
DEF PHONE_CONTACT_SCRIPT2_TIME   rb
DEF PHONE_CONTACT_SCRIPT2_BANK   rb
DEF PHONE_CONTACT_SCRIPT2_ADDR   rw
DEF PHONE_CONTACT_SIZE EQU _RS

; Legacy intended limit; the bitset-backed phone list is catalog-sized.
DEF CONTACT_LIST_SIZE EQU 30

; The catalog and saved phone-list capacity may grow independently.
DEF PHONE_FLAG_BASE_BYTES EQU 5
DEF PHONE_FLAG_EXTENSION_BYTES EQU 3
DEF PHONE_FLAG_BYTES EQU PHONE_FLAG_BASE_BYTES + PHONE_FLAG_EXTENSION_BYTES
DEF PHONE_FLAG_CAPACITY EQU PHONE_FLAG_BYTES * 8
; ASCII "PHN2"; four bytes make accidental matches in legacy padding negligible.
DEF PHONE_STORAGE_MAGIC_1 EQU $50
DEF PHONE_STORAGE_MAGIC_2 EQU $48
DEF PHONE_STORAGE_MAGIC_3 EQU $4e
DEF PHONE_STORAGE_MAGIC_4 EQU $32

	assert NUM_PHONE_CONTACTS <= PHONE_FLAG_CAPACITY
