; PhoneContacts indexes (see data/phone/phone_contacts.asm)
	const_def
	const PHONE_00
	const PHONE_MOM
	const PHONE_OAK
	const PHONE_BILL
	const PHONE_ELM
	const PHONE_LYRA
	const PHONE_SCHOOLBOY_JACK
	const PHONE_POKEFAN_BEVERLY
	const PHONE_SAILOR_HUEY
	const_skip
	const_skip
	const PHONE_COOLTRAINERM_GAVEN
	const PHONE_COOLTRAINERF_BETH
	const PHONE_BIRDKEEPER_JOSE
	const PHONE_COOLTRAINERF_REENA
	const PHONE_YOUNGSTER_JOEY
	const PHONE_BUG_CATCHER_WADE
	const PHONE_FISHER_RALPH
	const PHONE_PICNICKER_LIZ
	const PHONE_HIKER_ANTHONY
	const PHONE_CAMPER_TODD
	const PHONE_PICNICKER_GINA
	const PHONE_JUGGLER_IRWIN
	const PHONE_BUG_CATCHER_ARNIE
	const PHONE_SCHOOLBOY_ALAN
	const_skip
	const PHONE_LASS_DANA
	const PHONE_SCHOOLBOY_CHAD
	const PHONE_POKEFANM_DEREK
	const PHONE_FISHER_TULLY
	const PHONE_POKEMANIAC_BRENT
	const PHONE_PICNICKER_TIFFANY
	const PHONE_BIRDKEEPER_VANCE
	const PHONE_FISHER_WILTON
	const PHONE_BLACKBELT_KENJI
	const PHONE_HIKER_PARRY
	const PHONE_PICNICKER_ERIN
	const PHONE_BUENA
DEF NUM_PHONE_CONTACTS EQU const_value - 1

; wDailyRematchFlags indexes
; Keep this order in sync with the legacy ENGINE_*_READY_FOR_REMATCH flags.
	const_def
	const REMATCH_CONTACT_JACK
	const REMATCH_CONTACT_HUEY
	const REMATCH_CONTACT_GAVEN
	const REMATCH_CONTACT_BETH
	const REMATCH_CONTACT_JOSE
	const REMATCH_CONTACT_REENA
	const REMATCH_CONTACT_JOEY
	const REMATCH_CONTACT_WADE
	const REMATCH_CONTACT_RALPH
	const REMATCH_CONTACT_LIZ
	const REMATCH_CONTACT_ANTHONY
	const REMATCH_CONTACT_TODD
	const REMATCH_CONTACT_GINA
	const REMATCH_CONTACT_ARNIE
	const REMATCH_CONTACT_ALAN
	const REMATCH_CONTACT_DANA
	const REMATCH_CONTACT_CHAD
	const REMATCH_CONTACT_TULLY
	const REMATCH_CONTACT_BRENT
	const REMATCH_CONTACT_TIFFANY
	const REMATCH_CONTACT_VANCE
	const REMATCH_CONTACT_WILTON
	const REMATCH_CONTACT_PARRY
	const REMATCH_CONTACT_ERIN
DEF NUM_REMATCH_CONTACTS EQU const_value

DEF REMATCH_FLAG_BYTES EQU 4
DEF REMATCH_FLAG_CAPACITY EQU REMATCH_FLAG_BYTES * 8

	assert NUM_REMATCH_CONTACTS == 24
	assert NUM_REMATCH_CONTACTS <= REMATCH_FLAG_CAPACITY
	assert ENGINE_HUEY_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_HUEY
	assert ENGINE_GAVEN_READY_FOR_REMATCH  == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_GAVEN
	assert ENGINE_BETH_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_BETH
	assert ENGINE_JOSE_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_JOSE
	assert ENGINE_REENA_READY_FOR_REMATCH  == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_REENA
	assert ENGINE_JOEY_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_JOEY
	assert ENGINE_WADE_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_WADE
	assert ENGINE_RALPH_READY_FOR_REMATCH  == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_RALPH
	assert ENGINE_LIZ_READY_FOR_REMATCH    == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_LIZ
	assert ENGINE_ANTHONY_READY_FOR_REMATCH == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_ANTHONY
	assert ENGINE_TODD_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_TODD
	assert ENGINE_GINA_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_GINA
	assert ENGINE_ARNIE_READY_FOR_REMATCH  == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_ARNIE
	assert ENGINE_ALAN_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_ALAN
	assert ENGINE_DANA_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_DANA
	assert ENGINE_CHAD_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_CHAD
	assert ENGINE_TULLY_READY_FOR_REMATCH  == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_TULLY
	assert ENGINE_BRENT_READY_FOR_REMATCH  == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_BRENT
	assert ENGINE_TIFFANY_READY_FOR_REMATCH == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_TIFFANY
	assert ENGINE_VANCE_READY_FOR_REMATCH  == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_VANCE
	assert ENGINE_WILTON_READY_FOR_REMATCH == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_WILTON
	assert ENGINE_PARRY_READY_FOR_REMATCH  == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_PARRY
	assert ENGINE_ERIN_READY_FOR_REMATCH   == ENGINE_JACK_READY_FOR_REMATCH + REMATCH_CONTACT_ERIN
	assert ENGINE_ERIN_READY_FOR_REMATCH - ENGINE_JACK_READY_FOR_REMATCH + 1 == NUM_REMATCH_CONTACTS

; SpecialPhoneCallList indexes (see data/phone/special_calls.asm)
	const_def
	const SPECIALCALL_NONE
	const SPECIALCALL_POKERUS
	const SPECIALCALL_ROBBED
	const SPECIALCALL_ASSISTANT
	const SPECIALCALL_WEIRDBROADCAST
	const SPECIALCALL_SSTICKET
	const SPECIALCALL_BIKESHOP
	const SPECIALCALL_WORRIED
	const SPECIALCALL_MASTERBALL
	const SPECIALCALL_YELLOWFOREST
	const SPECIALCALL_FIRSTBADGE
	const SPECIALCALL_SECONDBADGE
	const SPECIALCALL_LYRASEGG
DEF NUM_SPECIALCALLS EQU const_value - 1
DEF SPECIALCALL_SIZE EQU 6

; phone struct members
rsreset
DEF PHONE_CONTACT_TRAINER_CLASS  rb
DEF PHONE_CONTACT_TRAINER_NUMBER rb
DEF PHONE_CONTACT_MAP_GROUP      rb
DEF PHONE_CONTACT_MAP_NUMBER     rb
DEF PHONE_CONTACT_SCRIPT1_TIME   rb
DEF PHONE_CONTACT_SCRIPT1_BANK   rb
DEF PHONE_CONTACT_SCRIPT1_ADDR   rw
DEF PHONE_CONTACT_SCRIPT2_TIME   rb
DEF PHONE_CONTACT_SCRIPT2_BANK   rb
DEF PHONE_CONTACT_SCRIPT2_ADDR   rw
DEF PHONE_CONTACT_SIZE EQU _RS

; maximum number of pokegear contacts
DEF CONTACT_LIST_SIZE EQU 30
