; Stable active swarm IDs. Zero is reserved for no active swarm.
	const_def
	const SWARM_NONE
	const SWARM_DUNSPARCE_ID
	const SWARM_YANMA_ID
	const SWARM_QWILFISH_ID
	const SWARM_MARILL_ID
	const SWARM_MAGNEMITE_ID
	const SWARM_CHINCHOU_ID
	const SWARM_REMORAID_ID
	const SWARM_PHANPY_ID
	const SWARM_CATERPIE_ID
	const SWARM_SPINARAK_ID
	const SWARM_PARAS_ID
	const SWARM_HOPPIP_ID
	const SWARM_DITTO_ID
	const SWARM_SUNKERN_ID
	const SWARM_VULPIX_ID
	const SWARM_MILTANK_ID
	const SWARM_SANDSHREW_ID
	const SWARM_EKANS_ID
	const SWARM_SMEARGLE_ID
	const SWARM_HORSEA_ID
	const SWARM_MANKEY_ID
	const SWARM_PONYTA_ID
	const SWARM_DIGLETT_ID
	const SWARM_DRATINI_ID
	const SWARM_SWINUB_ID
	const SWARM_GLIGAR_ID
	const SWARM_PSYDUCK_ID
	const SWARM_TEDDIURSA_ID
	const SWARM_BELLSPROUT_ID
	const SWARM_MACHOP_ID
	const SWARM_TAUROS_ID
	const SWARM_CORSOLA_ID
	const SWARM_LICKITUNG_ID
	const SWARM_SLOWPOKE_ID
	const SWARM_WEEDLE_ID
	const SWARM_LEDYBA_ID
	const SWARM_ODDISH_ID
	const SWARM_PINECO_ID
	const SWARM_DROWZEE_ID
	const SWARM_VENONAT_ID
	const SWARM_GROWLITHE_ID
	const SWARM_STANTLER_ID
	const SWARM_WOOPER_ID
	const SWARM_AIPOM_ID
	const SWARM_KOFFING_ID
	const SWARM_MANTINE_ID
	const SWARM_MAREEP_ID
	const SWARM_GIRAFARIG_ID
	const SWARM_HOUNDOUR_ID
	const SWARM_ONIX_ID
	const SWARM_SNEASEL_ID
	const SWARM_SKARMORY_ID
	const SWARM_GOLBAT_ID
	const SWARM_DODUO_ID
	const SWARM_FURRET_ID
	const SWARM_PIKACHU_ID
	const SWARM_MAGMAR_ID
	const SWARM_GEODUDE_ID
	const SWARM_JIGGLYPUFF_ID
	const SWARM_POLIWAG_ID
	const SWARM_MEOWTH_ID
	const SWARM_FEAROW_ID
	const SWARM_CUBONE_ID
	const SWARM_MURKROW_ID
	const SWARM_HAUNTER_ID
	const SWARM_SLUGMA_ID
	const SWARM_VOLTORB_ID
	const SWARM_NIDORINO_ID
	const SWARM_FARFETCH_D_ID
	const SWARM_STARYU_ID
	const SWARM_SEEL_ID
	const SWARM_RHYHORN_ID
	const SWARM_MR__MIME_ID
	const SWARM_RATICATE_ID
	const SWARM_BULBASAUR_ID
	const SWARM_CHARMANDER_ID
	const SWARM_CLEFAIRY_ID
	const SWARM_NOCTOWL_ID
	const SWARM_ABRA_ID
	const SWARM_PIDGEOTTO_ID
	const SWARM_SQUIRTLE_ID
	const SWARM_KANGASKHAN_ID
	const SWARM_ELECTABUZZ_ID
	const SWARM_TYROGUE_ID
	const SWARM_GRIMER_ID
	const SWARM_EXEGGCUTE_ID
	const SWARM_NIDORINA_ID
	const SWARM_CHANSEY_ID
	const SWARM_SHELLDER_ID
	const SWARM_JYNX_ID
DEF NUM_SWARMS EQU const_value - 1

static_assert SWARM_NONE == 0
static_assert SWARM_DUNSPARCE_ID == 1
static_assert SWARM_YANMA_ID == 2
static_assert SWARM_QWILFISH_ID == 3
static_assert SWARM_GLIGAR_ID - SWARM_DUNSPARCE_ID + 1 == 26
static_assert SWARM_SKARMORY_ID - SWARM_PSYDUCK_ID + 1 == 26
static_assert SWARM_SEEL_ID - SWARM_GOLBAT_ID + 1 == 19
static_assert SWARM_JYNX_ID - SWARM_RHYHORN_ID + 1 == 19
static_assert NUM_SWARMS == 90
static_assert NUM_SWARMS < $100

; Script-facing activation results
	const_def
	const SWARM_ACTIVATE_BLOCKED
	const SWARM_ACTIVATE_NEW
	const SWARM_ACTIVATE_CURRENT

; Swarm encounter methods
	const_def
	const SWARM_METHOD_LAND
	const SWARM_METHOD_SURF
	const SWARM_METHOD_FISH
DEF NUM_SWARM_METHODS EQU const_value

; Swarm selection pools (bitmasks)
	const_def 0
	const SWARM_POOL_JOHTO_F
	const SWARM_POOL_KANTO_F
	const SWARM_POOL_JOHTO_ALT_F
	const SWARM_POOL_KANTO_ALT_F

DEF SWARM_POOL_JOHTO EQU 1 << SWARM_POOL_JOHTO_F
DEF SWARM_POOL_KANTO EQU 1 << SWARM_POOL_KANTO_F
DEF SWARM_POOL_JOHTO_ALT EQU 1 << SWARM_POOL_JOHTO_ALT_F
DEF SWARM_POOL_KANTO_ALT EQU 1 << SWARM_POOL_KANTO_ALT_F
DEF SWARM_POOL_ALL EQU SWARM_POOL_JOHTO | SWARM_POOL_KANTO | SWARM_POOL_JOHTO_ALT | SWARM_POOL_KANTO_ALT

static_assert SWARM_POOL_ALL == %1111

; Encounter profiles. Consumers interpret these according to the method.
	const_def
	const SWARM_PROFILE_DUNSPARCE
	const SWARM_PROFILE_YANMA
	const SWARM_PROFILE_QWILFISH
	const SWARM_PROFILE_MARILL
	const SWARM_PROFILE_MAGNEMITE
	const SWARM_PROFILE_CHINCHOU
	const SWARM_PROFILE_REMORAID
	const SWARM_PROFILE_PHANPY
	const SWARM_PROFILE_CATERPIE
	const SWARM_PROFILE_SPINARAK
	const SWARM_PROFILE_PARAS
	const SWARM_PROFILE_HOPPIP
	const SWARM_PROFILE_DITTO
	const SWARM_PROFILE_SUNKERN
	const SWARM_PROFILE_VULPIX
	const SWARM_PROFILE_MILTANK
	const SWARM_PROFILE_SANDSHREW
	const SWARM_PROFILE_EKANS
	const SWARM_PROFILE_SMEARGLE
	const SWARM_PROFILE_HORSEA
	const SWARM_PROFILE_MANKEY
	const SWARM_PROFILE_PONYTA
	const SWARM_PROFILE_DIGLETT
	const SWARM_PROFILE_DRATINI
	const SWARM_PROFILE_SWINUB
	const SWARM_PROFILE_GLIGAR
	const SWARM_PROFILE_PSYDUCK
	const SWARM_PROFILE_TEDDIURSA
	const SWARM_PROFILE_BELLSPROUT
	const SWARM_PROFILE_MACHOP
	const SWARM_PROFILE_TAUROS
	const SWARM_PROFILE_CORSOLA
	const SWARM_PROFILE_LICKITUNG
	const SWARM_PROFILE_SLOWPOKE
	const SWARM_PROFILE_WEEDLE
	const SWARM_PROFILE_LEDYBA
	const SWARM_PROFILE_ODDISH
	const SWARM_PROFILE_PINECO
	const SWARM_PROFILE_DROWZEE
	const SWARM_PROFILE_VENONAT
	const SWARM_PROFILE_GROWLITHE
	const SWARM_PROFILE_STANTLER
	const SWARM_PROFILE_WOOPER
	const SWARM_PROFILE_AIPOM
	const SWARM_PROFILE_KOFFING
	const SWARM_PROFILE_MANTINE
	const SWARM_PROFILE_MAREEP
	const SWARM_PROFILE_GIRAFARIG
	const SWARM_PROFILE_HOUNDOUR
	const SWARM_PROFILE_ONIX
	const SWARM_PROFILE_SNEASEL
	const SWARM_PROFILE_SKARMORY
	const SWARM_PROFILE_GOLBAT
	const SWARM_PROFILE_DODUO
	const SWARM_PROFILE_FURRET
	const SWARM_PROFILE_PIKACHU
	const SWARM_PROFILE_MAGMAR
	const SWARM_PROFILE_GEODUDE
	const SWARM_PROFILE_JIGGLYPUFF
	const SWARM_PROFILE_POLIWAG
	const SWARM_PROFILE_MEOWTH
	const SWARM_PROFILE_FEAROW
	const SWARM_PROFILE_CUBONE
	const SWARM_PROFILE_MURKROW
	const SWARM_PROFILE_HAUNTER
	const SWARM_PROFILE_SLUGMA
	const SWARM_PROFILE_VOLTORB
	const SWARM_PROFILE_NIDORINO
	const SWARM_PROFILE_FARFETCH_D
	const SWARM_PROFILE_STARYU
	const SWARM_PROFILE_SEEL
	const SWARM_PROFILE_RHYHORN
	const SWARM_PROFILE_MR__MIME
	const SWARM_PROFILE_RATICATE
	const SWARM_PROFILE_BULBASAUR
	const SWARM_PROFILE_CHARMANDER
	const SWARM_PROFILE_CLEFAIRY
	const SWARM_PROFILE_NOCTOWL
	const SWARM_PROFILE_ABRA
	const SWARM_PROFILE_PIDGEOTTO
	const SWARM_PROFILE_SQUIRTLE
	const SWARM_PROFILE_KANGASKHAN
	const SWARM_PROFILE_ELECTABUZZ
	const SWARM_PROFILE_TYROGUE
	const SWARM_PROFILE_GRIMER
	const SWARM_PROFILE_EXEGGCUTE
	const SWARM_PROFILE_NIDORINA
	const SWARM_PROFILE_CHANSEY
	const SWARM_PROFILE_SHELLDER
	const SWARM_PROFILE_JYNX
DEF NUM_SWARM_PROFILES EQU const_value

; Map scopes. A scope can contain one or more maps that share a swarm.
	const_def
	const SWARM_SCOPE_DARK_CAVE
	const SWARM_SCOPE_ROUTE_35
	const SWARM_SCOPE_ROUTE_32
	const SWARM_SCOPE_MOUNT_MORTAR
	const SWARM_SCOPE_ROUTE_38
	const SWARM_SCOPE_OLIVINE_CITY
	const SWARM_SCOPE_ROUTE_44
	const SWARM_SCOPE_ROUTE_46
	const SWARM_SCOPE_ROUTE_30
	const SWARM_SCOPE_ROUTE_31
	const SWARM_SCOPE_ILEX_FOREST
	const SWARM_SCOPE_ROUTE_29
	const SWARM_SCOPE_ROUTE_34
	const SWARM_SCOPE_NATIONAL_PARK
	const SWARM_SCOPE_ROUTE_36
	const SWARM_SCOPE_ROUTE_39
	const SWARM_SCOPE_UNION_CAVE
	const SWARM_SCOPE_ROUTE_33
	const SWARM_SCOPE_RUINS_OF_ALPH
	const SWARM_SCOPE_ROUTE_41
	const SWARM_SCOPE_ROUTE_42
	const SWARM_SCOPE_ROUTE_47
	const SWARM_SCOPE_ROUTE_48
	const SWARM_SCOPE_DRAGONS_DEN
	const SWARM_SCOPE_ICE_PATH
	const SWARM_SCOPE_ROUTE_45
	const SWARM_SCOPE_SLOWPOKE_WELL
	const SWARM_SCOPE_ROUTE_37
	const SWARM_SCOPE_BURNED_TOWER
	const SWARM_SCOPE_ROUTE_43
	const SWARM_SCOPE_CLIFF_CAVE
	const SWARM_SCOPE_VICTORY_ROAD
	const SWARM_SCOPE_ROUTE_26
	const SWARM_SCOPE_ROUTE_1
	const SWARM_SCOPE_VIRIDIAN_FOREST
	const SWARM_SCOPE_POKEMON_MANSION
	const SWARM_SCOPE_MOUNT_MOON
	const SWARM_SCOPE_ROUTE_5
	const SWARM_SCOPE_ROUTE_6
	const SWARM_SCOPE_ROUTE_11
	const SWARM_SCOPE_ROUTE_9
	const SWARM_SCOPE_ROCK_TUNNEL
	const SWARM_SCOPE_ROUTE_7
	const SWARM_SCOPE_ROUTE_8
	const SWARM_SCOPE_ROUTE_16
	const SWARM_SCOPE_ROUTE_10
	const SWARM_SCOPE_ROUTE_14
	const SWARM_SCOPE_ROUTE_13
	const SWARM_SCOPE_ROUTE_19
	const SWARM_SCOPE_SEAFOAM_ISLANDS
	const SWARM_SCOPE_ROUTE_21
	const SWARM_SCOPE_ROUTE_22
	const SWARM_SCOPE_ROUTE_25
	const SWARM_SCOPE_ROUTE_17
	const SWARM_SCOPE_ROUTE_15
	const SWARM_SCOPE_ROUTE_20
DEF NUM_SWARM_SCOPES EQU const_value

; Unlock rules. Rules are dispatched through SwarmUnlockRulePointers.
	const_def
	const SWARM_UNLOCK_NONE
DEF NUM_SWARM_UNLOCK_RULES EQU const_value

; Shiny policies.
	const_def
	const SWARM_SHINY_NORMAL
	const SWARM_SHINY_BOOSTED
DEF NUM_SWARM_SHINY_POLICIES EQU const_value

; SwarmData entry fields
	rsreset
DEF SWARMENTRY_SPECIES     rw
DEF SWARMENTRY_MAP_SCOPE   rb
DEF SWARMENTRY_LANDMARK    rb
DEF SWARMENTRY_METHOD      rb
DEF SWARMENTRY_POOL        rb
DEF SWARMENTRY_PROFILE     rb
DEF SWARMENTRY_UNLOCK_RULE rb
DEF SWARMENTRY_SHINY_POLICY rb
DEF SWARMENTRY_LENGTH EQU _RS

static_assert NUM_SWARM_PROFILES < $100
static_assert NUM_SWARM_PROFILES == NUM_SWARMS
static_assert SWARM_PROFILE_DUNSPARCE == SWARM_DUNSPARCE_ID - 1
static_assert SWARM_PROFILE_JYNX == SWARM_JYNX_ID - 1
static_assert NUM_SWARM_SCOPES < $100
static_assert NUM_SWARM_UNLOCK_RULES < $100
static_assert NUM_SWARM_SHINY_POLICIES < $100
